const regionlists=[
{'Bolivia' : 'Andean Latin America'},
{'Ecuador' : 'Andean Latin America'},
{'Peru' : 'Andean Latin America'},
{'Australia' : 'Australasia'},
{'New Zealand' : 'Australasia'},
{'Antigua and Barbuda' : 'Caribbean'},
{'Bahamas' : 'Caribbean'},
{'Belize' : 'Caribbean'},
{'Bermuda' : 'Caribbean'},
{'Barbados' : 'Caribbean'},
{'Cuba' : 'Caribbean'},
{'Dominica' : 'Caribbean'},
{'Dominican Republic' : 'Caribbean'},
{'Grenada' : 'Caribbean'},
{'Guyana' : 'Caribbean'},
{'Haiti' : 'Caribbean'},
{'Jamaica' : 'Caribbean'},
{'Saint Lucia' : 'Caribbean'},
{'Puerto Rico' : 'Caribbean'},
{'Suriname' : 'Caribbean'},
{'Trinidad and Tobago' : 'Caribbean'},
{'Saint Vincent and the Grenadines' : 'Caribbean'},
{'Armenia' : 'Central Asia'},
{'Azerbaijan' : 'Central Asia'},
{'Georgia' : 'Central Asia'},
{'Kazakhstan' : 'Central Asia'},
{'Kyrgyzstan' : 'Central Asia'},
{'Mongolia' : 'Central Asia'},
{'Tajikistan' : 'Central Asia'},
{'Turkmenistan' : 'Central Asia'},
{'Uzbekistan' : 'Central Asia'},
{'Albania' : 'Central Europe'},
{'Bulgaria' : 'Central Europe'},
{'Bosnia and Herzegovina' : 'Central Europe'},
{'Czech Republic' : 'Central Europe'},
{'Croatia' : 'Central Europe'},
{'Hungary' : 'Central Europe'},
{'Macedonia (TFYR)' : 'Central Europe'},
{'Montenegro' : 'Central Europe'},
{'Poland' : 'Central Europe'},
{'Romania' : 'Central Europe'},
{'Serbia' : 'Central Europe'},
{'Slovakia' : 'Central Europe'},
{'Slovenia' : 'Central Europe'},
{'Colombia' : 'Central Latin America'},
{'Costa Rica' : 'Central Latin America'},
{'Guatemala' : 'Central Latin America'},
{'Honduras' : 'Central Latin America'},
{'Mexico' : 'Central Latin America'},
{'Nicaragua' : 'Central Latin America'},
{'Panama' : 'Central Latin America'},
{'El Salvador' : 'Central Latin America'},
{'Venezuela' : 'Central Latin America'},
{'Angola' : 'Central Sub-Saharan Africa'},
{'Central African Republic' : 'Central Sub-Saharan Africa'},
{'DR Congo' : 'Central Sub-Saharan Africa'},
{'Congo' : 'Central Sub-Saharan Africa'},
{'Gabon' : 'Central Sub-Saharan Africa'},
{'Equatorial Guinea' : 'Central Sub-Saharan Africa'},
{'China' : 'East Asia'},
{'North Korea' : 'East Asia'},
{'Belarus' : 'Eastern Europe'},
{'Estonia' : 'Eastern Europe'},
{'Lithuania' : 'Eastern Europe'},
{'Latvia' : 'Eastern Europe'},
{'Moldova' : 'Eastern Europe'},
{'Russian Federation' : 'Eastern Europe'},
{'Ukraine' : 'Eastern Europe'},
{'Burundi' : 'Eastern Sub-Saharan Africa'},
{'Comoros' : 'Eastern Sub-Saharan Africa'},
{'Djibouti' : 'Eastern Sub-Saharan Africa'},
{'Eritrea' : 'Eastern Sub-Saharan Africa'},
{'Ethiopia' : 'Eastern Sub-Saharan Africa'},
{'Kenya' : 'Eastern Sub-Saharan Africa'},
{'Madagascar' : 'Eastern Sub-Saharan Africa'},
{'Mozambique' : 'Eastern Sub-Saharan Africa'},
{'Malawi' : 'Eastern Sub-Saharan Africa'},
{'Rwanda' : 'Eastern Sub-Saharan Africa'},
{'Somalia' : 'Eastern Sub-Saharan Africa'},
{'Tanzania' : 'Eastern Sub-Saharan Africa'},
{'Uganda' : 'Eastern Sub-Saharan Africa'},
{'Zambia' : 'Eastern Sub-Saharan Africa'},
{'Brunei Darussalam' : 'High-income Asia Pacific'},
{'Japan' : 'High-income Asia Pacific'},
{'South Korea' : 'High-income Asia Pacific'},
{'Singapore' : 'High-income Asia Pacific'},
{'Canada' : 'High-income North America'},
{'Greenland' : 'High-income North America'},
{'United States of America' : 'High-income North America'},
{'Afghanistan' : 'North Africa and Middle East'},
{'United Arab Emirates' : 'North Africa and Middle East'},
{'Bahrain' : 'North Africa and Middle East'},
{'Iran' : 'North Africa and Middle East'},
{'Iraq' : 'North Africa and Middle East'},
{'Jordan' : 'North Africa and Middle East'},
{'Kuwait' : 'North Africa and Middle East'},
{'Lebanon' : 'North Africa and Middle East'},
{'Oman' : 'North Africa and Middle East'},
{'Occupied Palestinian Territory' : 'North Africa and Middle East'},
{'Qatar' : 'North Africa and Middle East'},
{'Saudi Arabia' : 'North Africa and Middle East'},
{'Syrian Arab Republic' : 'North Africa and Middle East'},
{'Turkey' : 'North Africa and Middle East'},
{'Yemen' : 'North Africa and Middle East'},
{'Algeria' : 'North Africa and Middle East'},
{'Egypt. Libya' : 'North Africa and Middle East'},
{'Morocco' : 'North Africa and Middle East'},
{'Sudan' : 'North Africa and Middle East'},
{'Tunisia' : 'North Africa and Middle East'},
{'Fiji' : 'Oceania'},
{'Micronesia (Federated States of)' : 'Oceania'},
{'Kiribati' : 'Oceania'},
{'Marshall Islands' : 'Oceania'},
{'Papua New Guinea' : 'Oceania'},
{'Solomon Islands' : 'Oceania'},
{'Tonga' : 'Oceania'},
{'Vanuatu' : 'Oceania'},
{'Samoa' : 'Oceania'},
{'Bangladesh' : 'South Asia'},
{'Bhutan' : 'South Asia'},
{'India' : 'South Asia'},
{'Nepal' : 'South Asia'},
{'Pakistan' : 'South Asia'},
{'Indonesia' : 'Southeast Asia'},
{'Cambodia' : 'Southeast Asia'},
{'Lao PDR' : 'Southeast Asia'},
{'Sri Lanka' : 'Southeast Asia'},
{'Maldives' : 'Southeast Asia'},
{'Myanmar' : 'Southeast Asia'},
{'Malaysia' : 'Southeast Asia'},
{'Philippines' : 'Southeast Asia'},
{'Thailand' : 'Southeast Asia'},
{'Timor-Leste' : 'Southeast Asia'},
{'Viet Nam' : 'Southeast Asia'},
{'Mauritius' : 'Southeast Asia'},
{'Seychelles.' : 'Southeast Asia'},
{'Argentina' : 'Southern Latin America'},
{'Chile' : 'Southern Latin America'},
{'Uruguay' : 'Southern Latin America'},
{'Botswana' : 'Southern Sub-Saharan Africa'},
{'Lesotho' : 'Southern Sub-Saharan Africa'},
{'Namibia' : 'Southern Sub-Saharan Africa'},
{'Swaziland' : 'Southern Sub-Saharan Africa'},
{'South Africa' : 'Southern Sub-Saharan Africa'},
{'Zimbabwe' : 'Southern Sub-Saharan Africa'},
{'Brazil' : 'Tropical Latin America'},
{'Paraguay' : 'Tropical Latin America'},
{'Andorra' : 'Western Europe'},
{'Austria' : 'Western Europe'},
{'Belgium' : 'Western Europe'},
{'Switzerland' : 'Western Europe'},
{'Germany' : 'Western Europe'},
{'Denmark' : 'Western Europe'},
{'Spain' : 'Western Europe'},
{'Finland' : 'Western Europe'},
{'France' : 'Western Europe'},
{'United Kingdom' : 'Western Europe'},
{'Greece' : 'Western Europe'},
{'Ireland' : 'Western Europe'},
{'Iceland' : 'Western Europe'},
{'Italy' : 'Western Europe'},
{'Luxembourg' : 'Western Europe'},
{'Malta' : 'Western Europe'},
{'Netherlands' : 'Western Europe'},
{'Norway' : 'Western Europe'},
{'Portugal' : 'Western Europe'},
{'Sweden' : 'Western Europe'},
{'Cyprus' : 'Western Europe'},
{'Israel' : 'Western Europe'},
{'Benin' : 'Western Sub-Saharan Africa'},
{'Burkina Faso' : 'Western Sub-Saharan Africa'},
{'Cote d’Ivoire' : 'Western Sub-Saharan Africa'},
{'Cameroon' : 'Western Sub-Saharan Africa'},
{'Cabo Verde' : 'Western Sub-Saharan Africa'},
{'Ghana' : 'Western Sub-Saharan Africa'},
{'Guinea' : 'Western Sub-Saharan Africa'},
{'Gambia' : 'Western Sub-Saharan Africa'},
{'Guinea Bissau' : 'Western Sub-Saharan Africa'},
{'Liberia' : 'Western Sub-Saharan Africa'},
{'Mali' : 'Western Sub-Saharan Africa'},
{'Mauritania' : 'Western Sub-Saharan Africa'},
{'Niger' : 'Western Sub-Saharan Africa'},
{'Nigeria' : 'Western Sub-Saharan Africa'},
{'Senegal' : 'Western Sub-Saharan Africa'},
{'Sierra Leone' : 'Western Sub-Saharan Africa'},
{'Sao Tome and Principe' : 'Western Sub-Saharan Africa'},
{'Chad' : 'Western Sub-Saharan Africa'},
{'Togo' : 'Western Sub-Saharan Africa'}
]

export default regionlists;